[LangOptions]
LanguageName=Fran<00E7>ais
LanguageID=$040C
LanguageCodePage=1252
DialogFontName=Tahoma
TitleFontName=Arial
WelcomeFontName=Verdana
CopyrightFontName=Arial
DialogFontSize=8
TitleFontSize=29
WelcomeFontSize=12
CopyrightFontSize=8
