[LangOptions]
LanguageName=<D55C><AD6D><C5B4>
LanguageID=$0412
LanguageCodePage=949
DialogFontName=Tahoma
TitleFontName=Arial
WelcomeFontName=Verdana
CopyrightFontName=Arial
DialogFontSize=8
TitleFontSize=29
WelcomeFontSize=12
CopyrightFontSize=8
