[LangOptions]
LanguageName=Lietuvi<0173>
LanguageID=$0427
LanguageCodePage=1257
DialogFontName=Tahoma
TitleFontName=Arial
WelcomeFontName=Verdana
CopyrightFontName=Arial
DialogFontSize=8
TitleFontSize=29
WelcomeFontSize=12
CopyrightFontSize=8
