[LangOptions]
LanguageName=Slovenski
LanguageID=$0424
LanguageCodePage=1250
TitleFontName=Arial
WelcomeFontName=Verdana
CopyrightFontName=Arial
DialogFontSize=8
TitleFontSize=29
WelcomeFontSize=12
CopyrightFontSize=8
