[LangOptions]
LanguageName=Sloven<010D>ina
LanguageID=$041B
LanguageCodePage=1250
DialogFontName=Tahoma
TitleFontName=Arial
WelcomeFontName=Verdana
CopyrightFontName=Arial
DialogFontSize=8
TitleFontSize=29
WelcomeFontSize=12
CopyrightFontSize=8
