[LangOptions]
LanguageName=<7E41><9AD4><4E2D><6587>
LanguageID=$0404
LanguageCodePage=950
DialogFontName=新細明體
TitleFontName=Arial
WelcomeFontName=新細明體
CopyrightFontName=新細明體
DialogFontSize=9
TitleFontSize=28
WelcomeFontSize=12
CopyrightFontSize=9
