[LangOptions]
LanguageName=Valenci<00E0>
LanguageID=$8200
LanguageCodePage=1252
DialogFontName=Tahoma
TitleFontName=Arial
WelcomeFontName=Verdana
CopyrightFontName=Arial
DialogFontSize=8
TitleFontSize=29
WelcomeFontSize=12
CopyrightFontSize=8
